server:
  port: 8090
spring:
  data:
    mongodb:
      username: testUser
      password: testUser
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
